// The named SFX catalog — a browsable registry of popular sounds, all SYNTH:
// generated by the engine, license-clean, deterministic, tunable. The editor's
// audio tab lists these; renderSfx() previews.
//
// Scope is deliberately what synthesis nails — designed/abstract/tonal sounds
// (whoosh, impact, riser, UI, game, glitch, feedback). Organic human/crowd
// sounds (gasp, applause, cheering) want recordings, not synthesis, so they're
// intentionally out of this catalog rather than faked.

import {
  whoosh, impact, riser, downlifter, subDrop, pop, tick, sweep, glitch, shimmer, braam, type Sfx,
} from './sfx.js';
import { finish, type FinishOptions } from './finish.js';

const SR = 44100;

export interface SfxEntry {
  /** Unique id, e.g. "whoosh", "buzzer-wrong". */
  name: string;
  /** Display label. */
  label: string;
  /** transition · impact · riser · ui · feedback · game · magic · tech */
  category: string;
  tags: string[];
  /** Synth recipe — every catalog entry is generated. */
  make: (opts?: { tune?: number; seed?: number }) => Sfx;
}

// ── tiny tonal builder for the named "popular" synth sounds ───────────────────
interface Note { f: number; t: number; d: number; wave?: 'sine' | 'square' | 'saw'; gain?: number; }
function notesToSfx(notes: Note[], totalDur: number): Sfx {
  const N = Math.floor(totalDur * SR), buf = new Float32Array(N);
  for (const nt of notes) {
    const start = Math.floor(nt.t * SR), len = Math.floor(nt.d * SR), w = nt.wave ?? 'sine';
    let ph = 0;
    for (let i = 0; i < len; i++) {
      const tt = i / SR; ph += (2 * Math.PI * nt.f) / SR;
      let v: number;
      if (w === 'square') v = Math.sin(ph) >= 0 ? 0.7 : -0.7;
      else if (w === 'saw') { let s = 0; const K = Math.min(12, Math.floor(SR / 2 / nt.f)); for (let k = 1; k <= K; k++) s += Math.sin(k * ph) / k; v = s * 0.5; }
      else v = Math.sin(ph);
      const env = Math.exp(-tt / (nt.d * 0.4)) * Math.min(1, tt / 0.005);
      const idx = start + i; if (idx < N) buf[idx] += v * env * (nt.gain ?? 0.3);
    }
  }
  return { left: buf, right: Float32Array.from(buf), sampleRate: SR };
}
const sc = (o?: { tune?: number }): number => (o?.tune ?? 220) / 220; // scale to key

const dingCorrect = (o?: { tune?: number }): Sfx => { const t = sc(o); return notesToSfx([{ f: 880 * t, t: 0, d: 0.5 }, { f: 1320 * t, t: 0.08, d: 0.6 }], 0.7); };
const buzzerWrong = (o?: { tune?: number }): Sfx => { const t = sc(o); return notesToSfx([{ f: 150 * t, t: 0, d: 0.18, wave: 'square', gain: 0.32 }, { f: 145 * t, t: 0.22, d: 0.24, wave: 'square', gain: 0.32 }], 0.5); };
const notification = (o?: { tune?: number }): Sfx => { const t = sc(o); return notesToSfx([{ f: 1318 * t, t: 0, d: 0.22, gain: 0.28 }, { f: 1760 * t, t: 0.11, d: 0.4, gain: 0.28 }], 0.5); };
const powerUp = (o?: { tune?: number }): Sfx => { const t = sc(o); return notesToSfx([523, 659, 784, 1046].map((f, i) => ({ f: f * t, t: i * 0.06, d: 0.2, wave: 'saw' as const, gain: 0.22 })), 0.5); };
const coin = (o?: { tune?: number }): Sfx => { const t = sc(o); return notesToSfx([{ f: 988 * t, t: 0, d: 0.08, gain: 0.3 }, { f: 1318 * t, t: 0.06, d: 0.3, gain: 0.3 }], 0.4); };

export const SFX_CATALOG: SfxEntry[] = [
  { name: 'whoosh', label: 'Whoosh', category: 'transition', tags: ['swoosh', 'slide', 'transition'], make: (o) => whoosh({ tune: o?.tune, seed: o?.seed }) },
  { name: 'sweep', label: 'Sweep', category: 'transition', tags: ['filter', 'transition'], make: (o) => sweep({ seed: o?.seed }) },
  { name: 'impact', label: 'Impact / Hit', category: 'impact', tags: ['hit', 'boom', 'cut'], make: (o) => impact({ tune: o?.tune, seed: o?.seed }) },
  { name: 'boom', label: 'Boom / Sub Drop', category: 'impact', tags: ['sub', 'drop'], make: () => subDrop() },
  { name: 'braam', label: 'Braam (cinematic)', category: 'impact', tags: ['trailer', 'dread'], make: (o) => braam({ tune: o?.tune ?? 110, seed: o?.seed }) },
  { name: 'riser', label: 'Riser / Uplifter', category: 'riser', tags: ['build', 'tension'], make: (o) => riser({ tune: o?.tune, seed: o?.seed }) },
  { name: 'downlifter', label: 'Downlifter', category: 'riser', tags: ['downer', 'exit'], make: (o) => downlifter({ tune: o?.tune, seed: o?.seed }) },
  { name: 'pop', label: 'Pop', category: 'ui', tags: ['blip', 'appear'], make: (o) => pop({ tune: o?.tune, seed: o?.seed }) },
  { name: 'tick', label: 'Tick / Tap', category: 'ui', tags: ['click', 'counter'], make: (o) => tick({ tune: o?.tune, seed: o?.seed }) },
  { name: 'notification', label: 'Notification', category: 'ui', tags: ['alert', 'message'], make: (o) => notification(o) },
  { name: 'ding-correct', label: 'Correct / Ding', category: 'feedback', tags: ['right', 'success', 'chime'], make: (o) => dingCorrect(o) },
  { name: 'buzzer-wrong', label: 'Wrong Answer Buzzer', category: 'feedback', tags: ['wrong', 'error', 'buzz'], make: (o) => buzzerWrong(o) },
  { name: 'power-up', label: 'Power Up', category: 'game', tags: ['game', 'level up'], make: (o) => powerUp(o) },
  { name: 'coin', label: 'Coin / Pickup', category: 'game', tags: ['game', 'collect'], make: (o) => coin(o) },
  { name: 'shimmer', label: 'Shimmer / Sparkle', category: 'magic', tags: ['reveal', 'sparkle'], make: (o) => shimmer({ tune: o?.tune }) },
  { name: 'glitch', label: 'Glitch', category: 'tech', tags: ['digital', 'stutter'], make: (o) => glitch({ tune: o?.tune, seed: o?.seed }) },
];

/** The full catalog (for an editor audio tab to browse). */
export function listSfx(): SfxEntry[] { return SFX_CATALOG; }

/** Distinct categories in the catalog. */
export function sfxCategories(): string[] { return [...new Set(SFX_CATALOG.map((e) => e.category))]; }

export interface RenderSfxOptions { tune?: number; seed?: number; finish?: boolean | FinishOptions; }

/** Render a named SFX → stereo PCM, finished by default. Null for unknown names. */
export function renderSfx(name: string, opts: RenderSfxOptions = {}): Sfx | null {
  const e = SFX_CATALOG.find((x) => x.name === name);
  if (!e) return null;
  let s = e.make({ tune: opts.tune, seed: opts.seed });
  if (opts.finish !== false) s = finish(s, typeof opts.finish === 'object' ? opts.finish : undefined);
  return s;
}
